version: "3"

networks:
  mynetwork:

services:
  web:
    image: docker-node-mongo
    build: .
    command: "node app.js"
    ports:
      - "5000:5000"
    depends_on:
      - "mongo"
      - "contacts"
    networks:
      - mynetwork
  contacts:
    build:
      context: contacts
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    networks:
      - mynetwork
  mongo:
    image: "mongo"
    networks:
      - mynetwork
