version: "3"
services:
  mongo-seed:
    build: ./mongo-seed
    links:
      - mongo
  web:
    image: docker-node-mongo
    build: .
    command: "node app.js"
    ports:
      - "5000:5000"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
